# Generated by Django 5.2.12 on 2026-04-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0001_initial'),
        ('products', '0002_alter_product_options_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(related_name='products', to='allergens.allergen'),
        ),
    ]
