# Generated by Django 5.2.13 on 2026-04-25 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergens', '0001_initial'),
        ('products', '0005_alter_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='products/placeholder.png', upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.ManyToManyField(blank=True, related_name='products', to='allergens.allergen'),
        ),
    ]
