# Generated by Django 5.2.13 on 2026-05-15 01:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("allergens", "0001_initial"),
        ("categories", "0002_alter_category_slug"),
        ("products", "0006_product_image_alter_product_allergens"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Sale price when item is surplus or on discount",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="is_organic",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_surplus",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="low_stock_threshold",
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_organic"], name="products_pr_is_orga_97130f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_surplus"], name="products_pr_is_surp_1c858d_idx"
            ),
        ),
    ]
