# Generated by Django 5.2.13 on 2026-05-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0008_farmstory_recipe_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="farmstory",
            name="products",
            field=models.ManyToManyField(
                blank=True, related_name="farm_stories", to="products.product"
            ),
        ),
    ]
