# Generated by Django 5.2.13 on 2026-05-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_farmstory_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="season_end_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="season_start_month",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
