# Generated by Django 5.2.13 on 2026-05-10 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_parent_order_order_producer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("ready", "Ready"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refund_requested", "Refund Requested"),
                    ("refunded", "Refunded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="RefundRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason_category",
                    models.CharField(
                        choices=[
                            ("spoiled", "Spoiled/Damaged (100% or partial)"),
                            ("fresh_return", "Return Fresh Item (50% refund)"),
                            ("not_delivered", "Not Delivered/Cancel Before Delivery"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "reason_text",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Detailed explanation or 'Other' reason",
                    ),
                ),
                (
                    "evidence_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="refunds/evidence/"
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Calculated based on rules",
                        max_digits=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refund_requests",
                        to="orders.order",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Specific item if partial refund",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.orderitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
