# Generated by Django 5.2.13 on 2026-05-15 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_recurringorder_recurringorderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recurringorderitem",
            name="recurring_order",
        ),
        migrations.RemoveField(
            model_name="recurringorderitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="RecurringOrder",
        ),
        migrations.DeleteModel(
            name="RecurringOrderItem",
        ),
    ]
