name: Local
values:
  - key: base_url
    value: 'http://localhost:8000'
    enabled: true
  - key: auth_token
    value: ''
    enabled: true
  - key: customer_token
    value: ''
    enabled: true
  - key: producer_token
    value: ''
    enabled: true
  - key: cart_item_id
    value: ''
    enabled: true
  - key: order_id
    value: ''
    enabled: true
