name: Local
values:
  - key: base_url
    enabled: true
    value: 'http://localhost:8000'
  - key: auth_token
    enabled: true
    value: ''
  - key: customer_token
    enabled: true
    value: ''
  - key: producer_token
    enabled: true
    value: ''
  - key: cart_item_id
    enabled: true
    value: ''
  - key: order_id
    enabled: true
    value: ''
  - key: admin_token
    enabled: true
    value: ''
