# Generated by Django 5.2.13 on 2026-05-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customerprofile_postcode_producerprofile_postcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_community_group",
            field=models.BooleanField(default=False),
        ),
    ]
