[pytest]
DJANGO_SETTINGS_MODULE = core.settings
python_files = tests.py test_*.py *_tests.py
testpaths = apps
addopts = 
    --verbose
    --strict-markers
    --tb=short
    --cov=apps
    --cov-report=html
    --cov-report=term-missing
    -p no:warnings

markers =
    unit: Unit tests
    integration: Integration tests
    slow: Slow tests (e.g., external API calls)
    stripe: Tests using Stripe
