# Generated by Django 5.2.12 on 2026-04-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_phone_number_customerprofile_producerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='producerprofile',
            name='postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
