# Generated by Django 5.2.13 on 2026-04-27 07:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_parent_order_order_producer"),
        ("payments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("stripe_session_id", models.CharField(max_length=255, unique=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "network_commission",
                    models.DecimalField(
                        decimal_places=2, help_text="5% platform fee", max_digits=12
                    ),
                ),
                (
                    "producer_payout",
                    models.DecimalField(
                        decimal_places=2, help_text="95% to producers", max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("producer_breakdown", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        help_text="Linked after Stripe confirms payment",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_transaction",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["stripe_session_id"],
                        name="payments_pa_stripe__75394c_idx",
                    ),
                    models.Index(
                        fields=["status"], name="payments_pa_status_b6726a_idx"
                    ),
                    models.Index(
                        fields=["customer", "-created_at"],
                        name="payments_pa_custome_b9af5a_idx",
                    ),
                ],
            },
        ),
    ]
