# Generated by Django 5.2.13 on 2026-04-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymenttransaction"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="producerweeklysettlement",
            unique_together=set(),
        ),
    ]
