# Generated by Django 5.2.13 on 2026-05-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_producerweeklysettlement_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="delivery_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="is_recurring",
            field=models.BooleanField(default=False),
        ),
    ]
